name: CI

on:
  - push

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: npm -w packages/typeorm-logger-adaptor run build
      - run: npm run biome

      - run: npm run test

      - name: Upload test results
        uses: actions/upload-artifact@v7.0.1
        if: success() || failure()
        with:
          name: test-results
          path: packages/typeorm-logger-adaptor-test/reports/vitest-junit.xml

  test-package-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: packages/package-import-test/test.sh
