name: Test Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Jest Tests
          path: '*.xml'
          reporter: jest-junit
